// LAYOUT
export const HIDE_DRAWER = 'HIDE_DRAWER';
export const SHOW_DRAWER = 'SHOW_DRAWER';
// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// AUTH USER
export const AUTH_LOADING_TRUE = 'AUTH_LOADING_TRUE';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
// AFTER SIGNUP USER ACTIONS
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL';
// POSTS
export const GET_POST = 'GET_POST';
export const POSTS_LOADING_TRUE = 'POSTS_LOADING_TRUE';
export const GET_POSTS = 'GET_POSTS';
export const EMPTY_POSTS = 'EMPTY_POSTS';
export const CLEAR_POSTS = 'CLEAR_POSTS';
export const POSTS_ERROR = 'POSTS_ERROR';
// LIKE POST
export const UPDATE_POST_LIKES = 'UPDATE_POST_LIKES';
export const UPDATE_POSTS_LIKES = 'UPDATE_POSTS_LIKES';
// USERS
export const GET_USER = 'GET_USER';
export const USER_LOADING_TRUE = 'USER_LOADING_TRUE';
export const CLEAR_USER = 'CLEAR_USER';