// LAYOUT
export const HIDE_DRAWER = 'HIDE_DRAWER';
export const SHOW_DRAWER = 'SHOW_DRAWER';
// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// AUTH USER
export const AUTH_LOADING_TRUE = 'AUTH_LOADING_TRUE';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
// AFTER SIGNUP USER ACTIONS
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL';
// POSTS
export const POSTS_LOADING_TRUE = 'POSTS_LOADING_TRUE';
export const GET_POSTS = 'GET_POSTS';
export const POST_ERROR = 'POST_ERROR';
